name: trifold
description: Triflod mobile application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  #Firebase family
  firebase_auth: ^0.18.0+1
  firebase_core : ^0.5.0
  firebase_database: ^4.0.0
  flutter_svg: ^0.18.0
  google_sign_in: ^4.5.4

  #State Management
  provider: ^4.3.2+2
  stacked: ^1.7.6

  # UI
  auto_route: ^0.6.7
  flutter_platform_widgets: ^0.60.2
  flutter_statusbar_text_color: ^0.1.2

  #Utilities
  built_value: ^7.1.0
  built_collection: ^4.3.2
  connectivity: ^0.4.9
  device_info: ^0.4.2+4
  dio: ^3.0.9
  flutter_swiper: ^1.1.6
  get_it: ^4.0.4
  get: ^3.11.1
  intl: ^0.16.1
  logging: ^0.11.4
  random_string: ^2.1.0
  share: ^0.6.5
  shared_preferences: '>=0.5.8 <2.0.0'
  stacked_services: ^0.5.4+3
  url_launcher: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.0
  built_value_generator: ^7.1.0
  auto_route_generator: ^0.6.8
  logger: ^0.9.2


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/poppins/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.otf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Regular.otf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.otf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Bold.otf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-ExtraBold.otf
          weight: 600
